### ISSUE TITLE
[07.30] 컨퍼런스 Teaser 영상

### ISSUE THREAD

**Issue by becxer** [socc-io/kanban#25]

**Comment by becxer** [comment]
티저 페이스북에 게재 해도 될것 같네요

**Comment by oh4851** [comment]
네 민지찡이 말한대로 자막 크기만 조절하고 업로드 할 계획입니다.
(업로드 일정은 얘기를 해봐야 할 것 같아요)

**Comment by oh4851** [comment]
__TODO__

<공통>
- 게재 날짜 선정
---
- 문제소개: 자막 크기 수정
- 컨퍼런스소개:  배경음악 선정, 뇌로쏙 페이지 수정, B영역(연사 섭외 -> 템플릿 채우기)

**Comment by oh4851** [comment]
[7.30] 문제 티저 게재
[8.05] 컨퍼런스 티저 게재
