### ISSUE TITLE
입간판 제작단가 알아보기

### ISSUE THREAD

**Issue by becxer** [socc-io/kanban#33]
입간판 제작시에  컨퍼런스 특화 보다는 쏙의 케릭터 모양으로가 좋을것 같아요

**Comment by becxer** [comment]
입간판  메르츠 타워에 이미 있으므로 생략 (나중을 위해 제작 할까요?)

**Comment by Jisu-Lee** [comment]
아니에요. 당분간 D2 STARTUP FACTORY 계속 쓸 것 같은데 일단은 제작하지 않는게 좋을 것 같아요.
