### ISSUE TITLE
재미있는 알고리즘 문제 4개 와 해답준비

### ISSUE THREAD

**Issue by becxer** [socc-io/kanban#39]
재미있는 알고리즘 문제 4개 와 해답준비

**Comment by becxer** [comment]
@leejisu  이거는 대략 어떤 스타일의 문제를 준비하면 되나요? 알고스터디?

**Comment by Jisu-Lee** [comment]
아 어떤 스타일이냐면 "쉬운데 풀이는 여러 가지가 나올 수 있는 문제"에요. 딱 봤을 때 '오, 해볼만한데? 쉬운데?' 이런 생각이 드는 것이 좋아요.하지만 한 문제 정도는 좀 어려운 문제를 뽑아도 될 것 같아요.

**Comment by becxer** [comment]
준비했습니다 알고스터디 이슈에 올렸어요!!
